### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by martinwhl** [shevkunov/overlapping-spaces-for-compact-graph-representations#1]
Hi,

Thanks for the great work. However, I run into some errors when trying to run the code, and it seems that there is some data missing, for example, "./true_dssm/req_ans_learn.tsv". Could you please provide the data? Thanks a lot!

**Comment by shevkunov** [comment]
Unfortunately, as stated in the article in section 5.2, this dataset is private and I am not allowed to publish this data in the public domain. If you know about an open dataset that is similar in size and content, please let me know.
